### ISSUE TITLE
Error running openSMILE

### ISSUE THREAD

**Issue by cbare** [binarybottle/mhealthx#13]
```
root@master:~# mhealthx --phonation syn4590865 -t /home/ubuntu --plugin SGEGraph --plugin_args "dict(dont_resubmit_completed_jobs=True)" --cache /shared/software/mhealthx_cache  --output /shared/software/mhealthx_output --input /shared/software/mhealthx_cache/mhealthxprep --stop 10
Welcome, Christopher Bare!
/home/ubuntu/miniconda/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
/home/ubuntu/miniconda/lib/python2.7/site-packages/IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprecated. You should import from ipyparallel instead.
  "You should import from ipyparallel instead.", ShimWarning)
150913-01:52:01,663 workflow INFO:
	 ['check', 'execution', 'logging']
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/mhealthx", line 326, in <module>
    Flow.run(plugin=args.plugin, plugin_args=eval(args.plugin_args))
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 700, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 596, in run
    self._submit_graph(pyfiles, dependencies, nodes)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/sgegraph.py", line 101, in _submit_graph
    cmd.run()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1447, in _run_interface
    self.raise_exception(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1376, in raise_exception
    raise RuntimeError(message)
RuntimeError: Command:
bash /shared/software/mhealthx_cache/mhealthx/batch/submit_jobs.sh
Standard output:

Standard error:
/shared/software/mhealthx_cache/mhealthx/batch/submit_jobs.sh: line 2: j0_openSMILE.aI.a9=11: command not found
/shared/software/mhealthx_cache/mhealthx/batch/submit_jobs.sh: line 3: j1_openSMILE.aI.a6=12: command not found
/shared/software/mhealthx_cache/mhealthx/batch/submit_jobs.sh: line 4: j2_openSMILE.aI.a2=13: command not found
/shared/software/mhealthx_cache/mhealthx/batch/submit_jobs.sh: line 5: j3_openSMILE.aI.a5=14: command not found
/shared/software/mhealthx_cache/mhealthx/batch/submit_jobs.sh: line 6: j4_openSMILE.aI.a4=15: command not found
/shared/software/mhealthx_cache/mhealthx/batch/submit_jobs.sh: line 7: j5_openSMILE.aI.a3=16: command not found
/shared/software/mhealthx_cache/mhealthx/batch/submit_jobs.sh: line 8: j6_openSMILE.aI.a8=17: command not found
/shared/software/mhealthx_cache/mhealthx/batch/submit_jobs.sh: line 9: j7_openSMILE.aI.a1=18: command not found
/shared/software/mhealthx_cache/mhealthx/batch/submit_jobs.sh: line 10: j8_openSMILE.aI.a7=19: command not found
/shared/software/mhealthx_cache/mhealthx/batch/submit_jobs.sh: line 11: j9_openSMILE.aI.a0=20: command not found

Return code: 127
Interface CommandLine failed to run. 
root@master:~# mhealthx --phonation syn4590865 -t /home/ubuntu --plugin SGE --cache /shared/software/mhealthx_cache  --output /shared/software/mhealthx_output --input /shared/software/mhealthx_cache/mhealthxprep --stop 10
Welcome, Christopher Bare!
/home/ubuntu/miniconda/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
/home/ubuntu/miniconda/lib/python2.7/site-packages/IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprecated. You should import from ipyparallel instead.
  "You should import from ipyparallel instead.", ShimWarning)
150913-01:52:51,718 workflow INFO:
	 ['check', 'execution', 'logging']
150913-01:52:51,728 workflow INFO:
	 Running in parallel.
150913-01:52:51,731 workflow INFO:
	 Submitting 10 jobs
150913-01:52:51,731 workflow INFO:
	 Executing: openSMILE.aI.a5 ID: 0
150913-01:52:51,789 workflow INFO:
	 Executing: openSMILE.aI.a3 ID: 1
150913-01:52:51,846 workflow INFO:
	 Executing: openSMILE.aI.a8 ID: 2
150913-01:52:51,902 workflow INFO:
	 Executing: openSMILE.aI.a4 ID: 3
150913-01:52:51,958 workflow INFO:
	 Executing: openSMILE.aI.a1 ID: 4
150913-01:52:52,14 workflow INFO:
	 Executing: openSMILE.aI.a7 ID: 5
150913-01:52:52,70 workflow INFO:
	 Executing: openSMILE.aI.a6 ID: 6
150913-01:52:52,127 workflow INFO:
	 Executing: openSMILE.aI.a0 ID: 7
150913-01:52:52,183 workflow INFO:
	 Executing: openSMILE.aI.a9 ID: 8
150913-01:52:52,239 workflow INFO:
	 Executing: openSMILE.aI.a2 ID: 9
150913-01:53:08,659 workflow ERROR:
	 ['Node openSMILE.aI.a5 failed to run on host node013.']
150913-01:53:08,660 workflow INFO:
	 Saving crash info to /root/crash-20150913-015308-root-openSMILE.aI.a5.pklz
150913-01:53:08,660 workflow INFO:
	 Traceback (most recent call last):
  File "/shared/software/mhealthx_cache/mhealthx/batch/pyscript_20150913_015251_mhealthx_openSMILE.aI.a5.py", line 26, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 130, in openSMILE
TypeError: sequence item 0: expected string, NoneType found
Interface Function failed to run. 

150913-01:53:08,704 workflow ERROR:
	 ['Node openSMILE.aI.a3 failed to run on host node015.']
150913-01:53:08,704 workflow INFO:
	 Saving crash info to /root/crash-20150913-015308-root-openSMILE.aI.a3.pklz
150913-01:53:08,704 workflow INFO:
	 Traceback (most recent call last):
  File "/shared/software/mhealthx_cache/mhealthx/batch/pyscript_20150913_015251_mhealthx_openSMILE.aI.a3.py", line 26, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 130, in openSMILE
TypeError: sequence item 0: expected string, NoneType found
Interface Function failed to run. 

150913-01:53:08,791 workflow ERROR:
	 ['Node openSMILE.aI.a4 failed to run on host node012.']
150913-01:53:08,791 workflow INFO:
	 Saving crash info to /root/crash-20150913-015308-root-openSMILE.aI.a4.pklz
150913-01:53:08,791 workflow INFO:
	 Traceback (most recent call last):
  File "/shared/software/mhealthx_cache/mhealthx/batch/pyscript_20150913_015251_mhealthx_openSMILE.aI.a4.py", line 26, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 130, in openSMILE
TypeError: sequence item 0: expected string, NoneType found
Interface Function failed to run. 

150913-01:53:08,872 workflow ERROR:
	 ['Node openSMILE.aI.a7 failed to run on host node014.']
150913-01:53:08,873 workflow INFO:
	 Saving crash info to /root/crash-20150913-015308-root-openSMILE.aI.a7.pklz
150913-01:53:08,873 workflow INFO:
	 Traceback (most recent call last):
  File "/shared/software/mhealthx_cache/mhealthx/batch/pyscript_20150913_015252_mhealthx_openSMILE.aI.a7.py", line 26, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 130, in openSMILE
TypeError: sequence item 0: expected string, NoneType found
Interface Function failed to run. 

150913-01:53:08,965 workflow ERROR:
	 ['Node openSMILE.aI.a6 failed to run on host node006.']
150913-01:53:08,966 workflow INFO:
	 Saving crash info to /root/crash-20150913-015308-root-openSMILE.aI.a6.pklz
150913-01:53:08,966 workflow INFO:
	 Traceback (most recent call last):
  File "/shared/software/mhealthx_cache/mhealthx/batch/pyscript_20150913_015252_mhealthx_openSMILE.aI.a6.py", line 26, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 130, in openSMILE
TypeError: sequence item 0: expected string, NoneType found
Interface Function failed to run. 

150913-01:53:09,12 workflow ERROR:
	 ['Node openSMILE.aI.a0 failed to run on host node018.']
150913-01:53:09,12 workflow INFO:
	 Saving crash info to /root/crash-20150913-015309-root-openSMILE.aI.a0.pklz
150913-01:53:09,12 workflow INFO:
	 Traceback (most recent call last):
  File "/shared/software/mhealthx_cache/mhealthx/batch/pyscript_20150913_015252_mhealthx_openSMILE.aI.a0.py", line 26, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 130, in openSMILE
TypeError: sequence item 0: expected string, NoneType found
Interface Function failed to run. 

150913-01:53:09,98 workflow ERROR:
	 ['Node openSMILE.aI.a2 failed to run on host node016.']
150913-01:53:09,98 workflow INFO:
	 Saving crash info to /root/crash-20150913-015309-root-openSMILE.aI.a2.pklz
150913-01:53:09,98 workflow INFO:
	 Traceback (most recent call last):
  File "/shared/software/mhealthx_cache/mhealthx/batch/pyscript_20150913_015252_mhealthx_openSMILE.aI.a2.py", line 26, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 130, in openSMILE
TypeError: sequence item 0: expected string, NoneType found
Interface Function failed to run. 

150913-01:53:11,147 workflow ERROR:
	 ['Node openSMILE.aI.a8 failed to run on host node003.']
150913-01:53:11,148 workflow INFO:
	 Saving crash info to /root/crash-20150913-015311-root-openSMILE.aI.a8.pklz
150913-01:53:11,148 workflow INFO:
	 Traceback (most recent call last):
  File "/shared/software/mhealthx_cache/mhealthx/batch/pyscript_20150913_015251_mhealthx_openSMILE.aI.a8.py", line 26, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 130, in openSMILE
TypeError: sequence item 0: expected string, NoneType found
Interface Function failed to run. 

150913-01:53:11,192 workflow ERROR:
	 ['Node openSMILE.aI.a1 failed to run on host node017.']
150913-01:53:11,193 workflow INFO:
	 Saving crash info to /root/crash-20150913-015311-root-openSMILE.aI.a1.pklz
150913-01:53:11,193 workflow INFO:
	 Traceback (most recent call last):
  File "/shared/software/mhealthx_cache/mhealthx/batch/pyscript_20150913_015251_mhealthx_openSMILE.aI.a1.py", line 26, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 130, in openSMILE
TypeError: sequence item 0: expected string, NoneType found
Interface Function failed to run. 

150913-01:53:11,239 workflow ERROR:
	 ['Node openSMILE.aI.a9 failed to run on host node001.']
150913-01:53:11,240 workflow INFO:
	 Saving crash info to /root/crash-20150913-015311-root-openSMILE.aI.a9.pklz
150913-01:53:11,240 workflow INFO:
	 Traceback (most recent call last):
  File "/shared/software/mhealthx_cache/mhealthx/batch/pyscript_20150913_015252_mhealthx_openSMILE.aI.a9.py", line 26, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 130, in openSMILE
TypeError: sequence item 0: expected string, NoneType found
Interface Function failed to run. 

150913-01:53:13,245 workflow INFO:
	 ***********************************
150913-01:53:13,245 workflow ERROR:
	 could not run node: mhealthx.openSMILE.aI.a5
150913-01:53:13,245 workflow INFO:
	 crashfile: /root/crash-20150913-015308-root-openSMILE.aI.a5.pklz
150913-01:53:13,246 workflow ERROR:
	 could not run node: mhealthx.openSMILE.aI.a3
150913-01:53:13,246 workflow INFO:
	 crashfile: /root/crash-20150913-015308-root-openSMILE.aI.a3.pklz
150913-01:53:13,246 workflow ERROR:
	 could not run node: mhealthx.openSMILE.aI.a4
150913-01:53:13,246 workflow INFO:
	 crashfile: /root/crash-20150913-015308-root-openSMILE.aI.a4.pklz
150913-01:53:13,246 workflow ERROR:
	 could not run node: mhealthx.openSMILE.aI.a7
150913-01:53:13,246 workflow INFO:
	 crashfile: /root/crash-20150913-015308-root-openSMILE.aI.a7.pklz
150913-01:53:13,246 workflow ERROR:
	 could not run node: mhealthx.openSMILE.aI.a6
150913-01:53:13,246 workflow INFO:
	 crashfile: /root/crash-20150913-015308-root-openSMILE.aI.a6.pklz
150913-01:53:13,246 workflow ERROR:
	 could not run node: mhealthx.openSMILE.aI.a0
150913-01:53:13,247 workflow INFO:
	 crashfile: /root/crash-20150913-015309-root-openSMILE.aI.a0.pklz
150913-01:53:13,247 workflow ERROR:
	 could not run node: mhealthx.openSMILE.aI.a2
150913-01:53:13,247 workflow INFO:
	 crashfile: /root/crash-20150913-015309-root-openSMILE.aI.a2.pklz
150913-01:53:13,247 workflow ERROR:
	 could not run node: mhealthx.openSMILE.aI.a8
150913-01:53:13,247 workflow INFO:
	 crashfile: /root/crash-20150913-015311-root-openSMILE.aI.a8.pklz
150913-01:53:13,247 workflow ERROR:
	 could not run node: mhealthx.openSMILE.aI.a1
150913-01:53:13,247 workflow INFO:
	 crashfile: /root/crash-20150913-015311-root-openSMILE.aI.a1.pklz
150913-01:53:13,247 workflow ERROR:
	 could not run node: mhealthx.openSMILE.aI.a9
150913-01:53:13,247 workflow INFO:
	 crashfile: /root/crash-20150913-015311-root-openSMILE.aI.a9.pklz
150913-01:53:13,248 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/mhealthx", line 328, in <module>
    Flow.run(plugin=args.plugin)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 700, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 268, in run
    report_nodes_not_run(notrun)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 92, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
```

**Comment by cbare** [comment]
The line in the generated python file that's failing is:
```
result = info['node'].run(updatehash=info['updatehash'])
```

**Comment by binarybottle** [comment]
Did you clear the cache directory?

**Comment by cbare** [comment]
yeah, I tried: ```rm -rf /shared/software/mhealthx_cache/mhealthx```. Is there something else I need to clear?

**Comment by binarybottle** [comment]
YES!  You need to re-run mhealthxprep!  Will this take long?

Cheers,
@rno

Arno Klein <http://binarybottle.com>
brain imaging, visualization
mobile health, open science
Sage Bionetworks <http://sagebase.org>

On Sat, Sep 12, 2015 at 10:27 PM, Christopher Bare <notifications@github.com

**Comment by cbare** [comment]
re-ran mhealthxprep, but still got the same error

**Comment by binarybottle** [comment]
Error was when a corrupt audio file did not convert, so a None was passed to:
argn=''.join([new_file, '.csv'])
Fixed by surrounding with a try, except.
