### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cbare** [binarybottle/mhealthx#9]
```
root@master:~# mhealthx --phonation syn4590865 -t /home/ubuntu --plugin SGEGraph --plugin_args "dict(dont_resubmit_completed_jobs=True)" --cache /root/mhealthx_cache --output /shared/software/mhealthx_cache --stop 10
Welcome, Christopher Bare!
/home/ubuntu/miniconda/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
/home/ubuntu/miniconda/lib/python2.7/site-packages/IPython/parallel.py:13: ShimWarning: The `IPython.parallel` package has been deprecated. You should import from ipyparallel instead.
  "You should import from ipyparallel instead.", ShimWarning)
150910-04:43:00,944 workflow INFO:
	 ['check', 'execution', 'logging']
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/mhealthx", line 446, in <module>
    Flow.run(plugin=args.plugin, plugin_args=eval(args.plugin_args))
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 700, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 596, in run
    self._submit_graph(pyfiles, dependencies, nodes)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/sgegraph.py", line 49, in _submit_graph
    batch_dir, _ = os.path.split(pyfiles[0])
IndexError: list index out of range
```

**Comment by binarybottle** [comment]
Looks like an index error related to sgegraph.  I don't get any error on my machine, so perhaps try without sgegraph and with sge for comparison...

**Comment by binarybottle** [comment]
@satra notes that saving to a local worker node's cache directory won't work -- work needs to be saved to the shared directory.
